# rate
rate_ros: 100.0

# model
model_base: "base_link"
model_odom: "odom"

# list
list_target:
  - "[1.5, 1.5]"
  - "[1.5, -1.5]"
  - "[-1.5, -1.5]"
  - "[-1.5, 1.5]"
list_interpolation: 1000
list_switch_dist: 0.1
list_inverse_flag: false
list_fixed_head: false
