# rate
rate_ros: 100.0

# model
model_base: "base_link"
model_odom: "odom"

# list
list_target:
  - "[1.5, 1.5, 0.0]"
  - "[1.5, -1.5, 0.0]"
  - "[-1.5, -1.5, 0.0]"
  - "[-1.5, 1.5, 0.0]"
switch_distance: 0.1
list_inverse_flag: false
