# rate
rate_ros: 200.0
rate_odom: 100.0

# model
model_base: "base_link"
model_odom: "odom"

# limit
limit_vel:
  # [vel_norm, omega]
  - 0.55
  - 1.0
limit_acc:
  # [acc_norm, alpha]
  - 5.0
  - 3.14

# obs
obs_weights: # weights of observation
  - 0.3
  - 0.3
  - 0.3
  - 0.3

# trace
trace_pid:
  # [kp_x, kp_y, kp_yaw]
  # [ki_x, ki_y, ki_yaw]
  # [kd_x, kd_y, kd_yaw]
  - "[100.0, 100.0, 100.0]"
  - "[0.0, 0.0, 0.0]"
  - "[20.0, 20.0, 30.0]"
trace_err_limit:
  # [pos_err, yaw_err]
  - 1.0
  - 2.0